/** The cultural rules a schema cannot state.
 *
 *  The spec schema constrains *shape* — which elements may be named, which
 *  sources may be cited, what numbers are in range. This file constrains
 *  *meaning*: whether an element is somewhere it belongs, whether a parameter
 *  has wandered outside what the sources actually document, whether the
 *  citations cover what the design claims.
 *
 *  It runs on every spec regardless of origin — generated by Claude, loaded
 *  from the catalog, decoded from a permalink, or produced by dragging a
 *  slider. A rule that only applied to AI output would be a rule about AI, and
 *  these are rules about Saudi architecture.
 *
 *  Errors block rendering. Warnings render and are shown in the inspector and
 *  on the share card — visible, never swallowed. */

import type { FacadeSpec } from "./schema";
import type { ApplicableSurface, CulturalElement, PlacementZone } from "@/types/element";
import { isOutsideDocumented } from "@/types/element";
import { elementById } from "@/data/corpus/elements";
import { sourceCovers } from "@/data/corpus/sources";
import { paletteHasMaterial, paletteById } from "@/data/corpus/palettes";
import { characterById } from "@/data/characters";

export type LintCode =
  | "unknown-element"
  | "unknown-param"
  | "param-out-of-range"
  | "param-outside-documented-range"
  | "placement-surface"
  | "placement-face"
  | "placement-zone"
  | "placement-count"
  | "source-coverage"
  | "provenance-incomplete"
  | "unknown-material"
  | "mass-overlap"
  | "mass-outside-plot"
  | "typology-mixing"
  | "court-not-enclosed"
  | "anchor-unused-element"
  | "manufacturability";

export interface LintIssue {
  code: LintCode;
  /** Where in the spec, in a form a person can find: "masses[1].faces[0]". */
  path: string;
  message: string;
}

export interface LintResult {
  errors: LintIssue[];
  warnings: LintIssue[];
  ok: boolean;
}

/** Which physical surface a placement lands on.
 *
 *  Note that a court-facing wall is still an *exterior* surface of the
 *  building — it is outdoors. That distinction is what makes the Al-Qatt rule
 *  bite: the element is restricted to `interior`, and a façade spec has no
 *  interior surfaces, so it cannot be placed anywhere in one. That is the
 *  correct outcome rather than an awkward one. */
function surfaceOf(exposure: string, zone: PlacementZone | undefined): ApplicableSurface {
  if (zone === "roof") return "roof";
  if (exposure === "court") return "court";
  return "exterior";
}

interface Placement {
  path: string;
  elementId: string;
  exposure: string;
  zone?: PlacementZone;
  params?: Record<string, number>;
  face?: string;
}

export function culturalLint(spec: FacadeSpec): LintResult {
  const errors: LintIssue[] = [];
  const warnings: LintIssue[] = [];
  const err = (code: LintCode, path: string, message: string) => errors.push({ code, path, message });
  const warn = (code: LintCode, path: string, message: string) => warnings.push({ code, path, message });

  const character = characterById(spec.characterId);
  const palette = paletteById(spec.palette.paletteId);

  // ── gather every element placement in one pass ───────────────────────────
  const placements: Placement[] = [];
  spec.masses.forEach((m, mi) => {
    m.faces.forEach((f, fi) => {
      f.elements.forEach((el, ei) => {
        placements.push({
          path: `masses[${mi}].faces[${fi}].elements[${ei}]`,
          elementId: el.elementId,
          exposure: f.exposure,
          zone: el.zone,
          params: el.params,
          face: f.face,
        });
      });
      f.openings.forEach((o, oi) => {
        if (o.elementId) {
          placements.push({
            path: `masses[${mi}].faces[${fi}].openings[${oi}]`,
            elementId: o.elementId,
            exposure: f.exposure,
            zone: "ground",
            params: o.params,
            face: f.face,
          });
        }
      });
    });
    (m.crown?.elementIds ?? []).forEach((id, ci) => {
      placements.push({
        path: `masses[${mi}].crown.elementIds[${ci}]`,
        elementId: id,
        exposure: "street",
        zone: "crown",
        params: m.crown?.params,
      });
    });
  });
  (spec.site.court?.elementIds ?? []).forEach((id, i) => {
    placements.push({
      path: `site.court.elementIds[${i}]`,
      elementId: id,
      exposure: "court",
      // The court is the ground plane itself, not a band on a wall. Elements
      // living here (hosh, riwaq, pool) declare `ground-plane` in their zone.
      zone: "ground-plane",
      params: spec.site.court?.params,
    });
  });

  // ── per-placement rules ──────────────────────────────────────────────────
  const perFaceCount = new Map<string, number>();

  for (const p of placements) {
    const el: CulturalElement | undefined = elementById(p.elementId);
    if (!el) {
      err("unknown-element", p.path, `"${p.elementId}" is not in the element library`);
      continue;
    }

    // Surface — the rule that carries the most cultural weight.
    const surface = surfaceOf(p.exposure, p.zone);
    if (!el.placement.surfaces.includes(surface)) {
      err(
        "placement-surface",
        p.path,
        `${el.name.en} is documented for ${el.placement.surfaces.join("/")} surfaces, ` +
          `but this places it on a ${surface} surface` +
          (el.placement.notes ? `. ${el.placement.notes.en}` : ""),
      );
    }

    // Face exposure.
    const faces = el.placement.faces;
    if (!faces.includes("any") && !faces.includes(p.exposure as never)) {
      err(
        "placement-face",
        p.path,
        `${el.name.en} belongs on ${faces.join("/")} faces, not a ${p.exposure} face`,
      );
    }

    // Vertical zone.
    if (p.zone && !el.placement.zone.includes(p.zone)) {
      err(
        "placement-zone",
        p.path,
        `${el.name.en} belongs in the ${el.placement.zone.join("/")} zone, not ${p.zone}`,
      );
    }

    // Instances per face.
    if (typeof el.placement.maxPerFace === "number" && p.face) {
      const key = `${p.face}:${el.id}`;
      const n = (perFaceCount.get(key) ?? 0) + 1;
      perFaceCount.set(key, n);
      if (n > el.placement.maxPerFace) {
        err(
          "placement-count",
          p.path,
          `${el.name.en} appears ${n} times on face ${p.face}; the documented maximum is ${el.placement.maxPerFace}`,
        );
      }
    }

    // Parameters: known keys, in range, and inside what the sources document.
    for (const [key, value] of Object.entries(p.params ?? {})) {
      const param = el.params.find((x) => x.key === key);
      if (!param) {
        err("unknown-param", p.path, `${el.name.en} has no parameter "${key}"`);
        continue;
      }
      if (value < param.min || value > param.max) {
        err(
          "param-out-of-range",
          p.path,
          `${el.name.en}.${key} = ${value} is outside [${param.min}, ${param.max}]`,
        );
      } else if (isOutsideDocumented(param, value)) {
        const [lo, hi] = param.documentedRange!;
        warn(
          "param-outside-documented-range",
          p.path,
          `${el.name.en}.${key} = ${value} is buildable but outside the documented range ` +
            `${lo}–${hi}; the result is a departure from the sources, not an example of them`,
        );
      }
    }

    // The element must actually be attested for this character and typology.
    // The narrowed request schema prevents this for generated specs; catalog
    // files and permalinks come through the general schema, so it is checked.
    const attested = el.attestedIn.some(
      (a) => a.characterId === spec.characterId && a.typologies.includes(spec.typology),
    );
    if (!attested) {
      err(
        "unknown-element",
        p.path,
        `${el.name.en} is not attested for ${spec.characterId} at the ${spec.typology} typology`,
      );
    }
  }

  // ── elements that are never documented together ─────────────────────────
  const usedIds = [...new Set(placements.map((p) => p.elementId))];
  for (let i = 0; i < usedIds.length; i += 1) {
    for (let j = i + 1; j < usedIds.length; j += 1) {
      const a = elementById(usedIds[i]);
      const b = elementById(usedIds[j]);
      if (!a || !b) continue;
      const aChars = new Set(a.attestedIn.map((x) => x.characterId));
      const shared = b.attestedIn.some((x) => aChars.has(x.characterId));
      if (!shared) {
        warn(
          "typology-mixing",
          "masses",
          `${a.name.en} and ${b.name.en} are not attested for any character in common; ` +
            `combining them is an invention rather than a regional reading`,
        );
      }
    }
  }

  // ── provenance must account for every element used ──────────────────────
  const covered = new Set(spec.provenance.derivedFrom.map((d) => d.elementId));
  for (const id of usedIds) {
    if (!covered.has(id)) {
      err(
        "provenance-incomplete",
        "provenance.derivedFrom",
        `the design uses "${id}" but does not say what documented reference it derives from`,
      );
    }
  }

  // ── a cited source must cover the character it is cited for ─────────────
  for (const d of spec.provenance.derivedFrom) {
    for (const c of d.citations) {
      if (!sourceCovers(c.sourceId, spec.characterId)) {
        err(
          "source-coverage",
          "provenance.derivedFrom",
          `"${c.sourceId}" is cited for ${spec.characterId}, but that source does not cover it`,
        );
      }
    }
  }

  // ── materials must exist in the chosen palette ──────────────────────────
  const checkMaterial = (m: string | undefined, path: string) => {
    if (!m) return;
    if (!paletteHasMaterial(spec.palette.paletteId, m)) {
      err("unknown-material", path, `"${m}" is not in palette "${spec.palette.paletteId}"`);
    }
  };
  spec.masses.forEach((m, mi) => {
    checkMaterial(m.material, `masses[${mi}].material`);
    m.faces.forEach((f, fi) =>
      f.elements.forEach((el, ei) =>
        checkMaterial(el.material, `masses[${mi}].faces[${fi}].elements[${ei}].material`),
      ),
    );
  });
  for (const key of Object.keys(spec.palette.overrides ?? {})) {
    checkMaterial(key, `palette.overrides.${key}`);
  }
  if (palette && !palette.characterIds.includes(spec.characterId)) {
    warn(
      "unknown-material",
      "palette.paletteId",
      `palette "${palette.id}" is not listed for ${spec.characterId}`,
    );
  }

  // ── geometry sanity ─────────────────────────────────────────────────────
  const [px0, py0, px1, py1] = spec.site.plot;
  const plot = { x0: Math.min(px0, px1), x1: Math.max(px0, px1), y0: Math.min(py0, py1), y1: Math.max(py0, py1) };
  const boxes = spec.masses.map((m, i) => {
    const [x0, y0, x1, y1] = m.footprint;
    return { i, id: m.id, x0: Math.min(x0, x1), x1: Math.max(x0, x1), y0: Math.min(y0, y1), y1: Math.max(y0, y1) };
  });
  for (const b of boxes) {
    if (b.x0 < plot.x0 || b.x1 > plot.x1 || b.y0 < plot.y0 || b.y1 > plot.y1) {
      err("mass-outside-plot", `masses[${b.i}].footprint`, `mass "${b.id}" extends beyond the plot`);
    }
  }
  for (let i = 0; i < boxes.length; i += 1) {
    for (let j = i + 1; j < boxes.length; j += 1) {
      const a = boxes[i];
      const b = boxes[j];
      const overlapX = Math.min(a.x1, b.x1) - Math.max(a.x0, b.x0);
      const overlapY = Math.min(a.y1, b.y1) - Math.max(a.y0, b.y0);
      // A shared wall is normal; genuine interpenetration is not.
      if (overlapX > 0.05 && overlapY > 0.05) {
        err(
          "mass-overlap",
          `masses[${a.i}].footprint`,
          `masses "${a.id}" and "${b.id}" overlap in plan by ${overlapX.toFixed(2)} x ${overlapY.toFixed(2)} m`,
        );
      }
    }
  }

  // ── privacy: a court character wants an enclosed court ─────────────────
  if (character?.climate.drivers.includes("privacy") && spec.site.court) {
    const c = spec.site.court.footprint;
    const cx0 = Math.min(c[0], c[2]);
    const cx1 = Math.max(c[0], c[2]);
    const cy0 = Math.min(c[1], c[3]);
    const cy1 = Math.max(c[1], c[3]);
    const touching = boxes.filter(
      (b) =>
        Math.min(b.x1, cx1) - Math.max(b.x0, cx0) > -0.2 &&
        Math.min(b.y1, cy1) - Math.max(b.y0, cy0) > -0.2,
    ).length;
    if (touching < 3) {
      warn(
        "court-not-enclosed",
        "site.court",
        `${spec.characterId} lists privacy as a climate driver, but the court is bounded by ` +
          `${touching} mass(es); the courtyard plan exists to enclose`,
      );
    }
  }

  // ── anchors should point at elements the design actually uses ──────────
  for (const [i, a] of spec.anchors.entries()) {
    if (!usedIds.includes(a.elementId)) {
      warn(
        "anchor-unused-element",
        `anchors[${i}]`,
        `anchor "${a.id}" names "${a.elementId}", which the design does not place anywhere`,
      );
    }
  }

  return { errors, warnings, ok: errors.length === 0 };
}

/** Whether a design could actually be cast as precast panels.
 *
 *  Kept separate from the cultural rules because it answers a different
 *  question and has a different consequence: a design that fails here is still
 *  a legitimate cultural interpretation, it simply cannot be exported as a
 *  panel schedule and is labelled "concept only". */
export interface ManufacturabilityLimits {
  maxPanelWidth: number;
  maxPanelHeight: number;
  minWallThickness: number;
  maxCantilever: number;
}

export const DEFAULT_LIMITS: ManufacturabilityLimits = {
  maxPanelWidth: 3.5,
  maxPanelHeight: 8,
  minWallThickness: 0.15,
  maxCantilever: 1.8,
};

export function manufacturabilityLint(
  spec: FacadeSpec,
  limits: ManufacturabilityLimits = DEFAULT_LIMITS,
): LintResult {
  const errors: LintIssue[] = [];
  spec.masses.forEach((m, mi) => {
    if (m.wallThickness < limits.minWallThickness) {
      errors.push({
        code: "manufacturability",
        path: `masses[${mi}].wallThickness`,
        message: `${m.wallThickness} m is below the ${limits.minWallThickness} m minimum for a cast panel`,
      });
    }
    const [x0, y0, x1, y1] = m.footprint;
    const width = Math.max(Math.abs(x1 - x0), Math.abs(y1 - y0));
    const height = m.storeys * m.storeyHeight;
    if (width > limits.maxPanelWidth && height > limits.maxPanelHeight) {
      errors.push({
        code: "manufacturability",
        path: `masses[${mi}]`,
        message:
          `mass "${m.id}" is ${width.toFixed(1)} x ${height.toFixed(1)} m; a single panel cannot ` +
          `exceed ${limits.maxPanelWidth} x ${limits.maxPanelHeight} m, so this needs a joint strategy`,
      });
    }
  });
  return { errors, warnings: [], ok: errors.length === 0 };
}
